# Generated by Django 4.1.3 on 2022-12-09 04:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=300)),
                ('property_location', models.CharField(max_length=150)),
                ('property_type', models.CharField(default='Villa', max_length=150)),
                ('buy_rent', models.CharField(default='Buy', max_length=150)),
                ('total_bedroom', models.IntegerField()),
                ('total_bathroom', models.IntegerField()),
                ('property_price', models.IntegerField()),
                ('property_listing', models.CharField(blank=True, default='Standard Listing', max_length=150, null=True)),
                ('property_area', models.IntegerField()),
                ('property_keyword', models.TextField(blank=True, null=True)),
                ('property_description', tinymce.models.HTMLField(blank=True, null=True)),
                ('property_video_link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_international_property', models.BooleanField(default=False)),
                ('property_image', models.ImageField(upload_to='media')),
                ('property_image_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_three', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_four', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_five', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_six', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_seven', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_eight', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_nine', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_ten', models.ImageField(blank=True, null=True, upload_to='media')),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('property_map_location', models.CharField(blank=True, max_length=150, null=True)),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('property_status', models.BooleanField(default=True)),
                ('water_and_electricity', models.CharField(default='Exclusive', max_length=150)),
                ('parking_slot', models.IntegerField(blank=True, null=True)),
                ('furnished_type', models.CharField(default='Furnished', max_length=150)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_standard', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True)),
                ('meta_keyword', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('ref_id', models.CharField(blank=True, max_length=200, null=True)),
                ('property_amenities', models.ManyToManyField(to='core.amenities')),
            ],
        ),
    ]
