# Generated by Django 4.1.3 on 2022-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_innerad_masterad_secondad_thirdad'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAdMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_one', models.ImageField(upload_to='media')),
                ('ad_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('ad_three', models.ImageField(blank=True, null=True, upload_to='media')),
                ('active', models.BooleanField(default=True)),
                ('ad_one_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_two_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_three_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecondAdMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_one', models.ImageField(upload_to='media')),
                ('ad_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('ad_three', models.ImageField(blank=True, null=True, upload_to='media')),
                ('active', models.BooleanField(default=True)),
                ('ad_one_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_two_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_three_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdAdMobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_one', models.ImageField(upload_to='media')),
                ('ad_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('ad_three', models.ImageField(blank=True, null=True, upload_to='media')),
                ('active', models.BooleanField(default=True)),
                ('ad_one_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_two_link', models.CharField(blank=True, max_length=200, null=True)),
                ('ad_three_link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
