# Generated by Django 4.1.3 on 2022-12-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_masteradmobile_secondadmobile_thirdadmobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('watsapp', models.IntegerField(blank=True, null=True)),
                ('property_location', models.CharField(max_length=150)),
                ('property_type', models.CharField(default='Villa', max_length=150)),
                ('furnished_type', models.CharField(default='Furnished', max_length=150)),
                ('property_description', models.TextField(blank=True, null=True)),
                ('property_price', models.IntegerField()),
                ('property_image', models.ImageField(upload_to='media')),
                ('property_image_two', models.ImageField(blank=True, null=True, upload_to='media')),
                ('property_image_three', models.ImageField(blank=True, null=True, upload_to='media')),
                ('country_code', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
