# Generated by Django 4.1.3 on 2022-12-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='request',
            name='watsapp',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
