# Generated by Django 4.1.3 on 2023-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_faqstatus_testimonialstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterad',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterad',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterad',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='faqstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonialstatus',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
