# Generated by Django 4.1.3 on 2023-01-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_masterad_ad_one_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterad',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterad',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masterad',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
    ]
