# Generated by Django 4.1.3 on 2023-01-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_masterad_ad_one_status_masterad_ad_three_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondad',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secondad',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secondad',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdad',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdad',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdad',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
    ]
