# Generated by Django 4.1.3 on 2023-01-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_secondad_ad_one_status_secondad_ad_three_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masteradmobile',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masteradmobile',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='masteradmobile',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secondadmobile',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secondadmobile',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='secondadmobile',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdadmobile',
            name='ad_one_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdadmobile',
            name='ad_three_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='thirdadmobile',
            name='ad_two_status',
            field=models.BooleanField(default=True),
        ),
    ]
